### ISSUE TITLE
不打算开通评论系统吗？

### ISSUE THREAD

**Issue by ngzhio** [keithnull/keithnull.github.io#1]

**Comment by izackwu** [comment]
考虑到国内备案的原因，不太方便在网页里加上评论；而且一般也没啥人评论吧😂

不过，其实这里的 Issues 就可以当作评论来用，如果愿意的话

**Comment by ngzhio** [comment]
你的网站是挂载 GitHub Pages 上的吗？如果是，那就不用考虑备案的事情。备案本就是对言论自由的践踏。

推荐使用 Disqus 评论系统，接入也很方便，只是国内需要翻墙才能使用。

**Comment by ngzhio** [comment]
Jeff Atwood 说过，[没有评论系统的博客不算博客](https://blog.codinghorror.com/a-blog-without-comments-is-not-a-blog/)。

**Comment by izackwu** [comment]
> 
> 
> 你的网站是挂载 GitHub Pages 上的吗？如果是，那就不用考虑备案的事情。备案本就是对言论自由的践踏。
> 
> 推荐使用 Disqus 评论系统，接入也很方便，只是国内需要翻墙才能使用。

网站本体托管在 Github Page，但是图片资源放在国内的 CDN 上，同时也有其他的原因，所以不得不备案。

> Jeff Atwood 说过，[没有评论系统的博客不算博客](https://blog.codinghorror.com/a-blog-without-comments-is-not-a-blog/)。

我不认识 Jeff Atwood，而且他的话我不认同。

**Comment by izackwu** [comment]
@ngzhio 

目前开通了 Gitalk 评论
