### ISSUE TITLE
优化目录显示

### ISSUE THREAD

**Issue by tianheg** [keithnull/keithnull.github.io#49]
文章目录在较小屏幕上不能完全显示：

<img width="660" alt="Snipaste_2021-01-05_17-59-57" src="https://user-images.githubusercontent.com/52186032/103633854-3c8a3c80-4f81-11eb-9c06-53517479ecbe.png">

**Comment by izackwu** [comment]
该问题属于已知问题：https://github.com/keithnull/gatsby-starter-breeze/issues/20#issue-709545278

目前来看，似乎没啥简单且效果好的解决办法，暂时先这样吧

~~建议用正常尺寸的设备浏览网页~~
